name: build

on:
    push:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write

        strategy:
            matrix:
                os: [windows-latest]

        steps:
            # Checkout the repository
            -   uses: actions/checkout@main

            # Set up Node.js
            -   uses: actions/setup-node@main
                with:
                    node-version: '22'

            # Install dependencies
            -   run: npm install

            # Build & Release
            -   uses: samuelmeuli/action-electron-builder@v1 
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    release: true